version: '3.8'

services:
  php:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=roots
      - POSTGRES_PASSWORD=vidyahgames
      - POSTGRES_DB=collections
